name:                oh-my-typo
version:             0.1.0.0
github:              "thoaionline/oh-my-typo"
license:             BSD3
author:              "Thoai Nguyen <me@thoaionline.com>"
maintainer:          "Thoai Nguyen <me@thoaionline.com>"
copyright:           "2019 Thoai Nguyen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thoaionline/oh-my-typo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  oh-my-typo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oh-my-typo

tests:
  oh-my-typo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oh-my-typo
